### ISSUE TITLE
Cannot submit assignment - missign module?

### ISSUE THREAD

**Issue by jcvdav** [UCSB-PSTAT-134-234/Spring2019#1]
Hi @syoh ,

I've been trying to submit the assignment since the weekend. After running all cells, I run the submit cell, and get an error.

```
# Save your notebook first, then run this cell to submit.
import jassign.to_pdf
jassign.to_pdf.generate_pdf('homework1.ipynb', 'homework1.pdf')
ok.submit()
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-43-7e60ec269b92> in <module>
      1 # Save your notebook first, then run this cell to submit.
----> 2 import jassign.to_pdf
      3 jassign.to_pdf.generate_pdf('homework1.ipynb', 'homework1.pdf')
      4 ok.submit()

ModuleNotFoundError: No module named 'jassign'
```

Looks like other students had no problems. For the record, I am running this on the [pstat134.lsit](https://pstat134.lsit.ucsb.edu/user/juancarlos/notebooks/Spring2019/homeworks/homework1/student/homework1.ipynb) server.

**Comment by jcvdav** [comment]
Fixed when updating README.md in https://github.com/UCSB-PSTAT-134-234/Spring2019/commit/c9e3f11fb6c8ffe6eec2c019cecc03a5cbc5b911#diff-04c6e90faac2675aa89e2176d2eec7d8R13

**Comment by syoh** [comment]
Sorry I wasn't monitoring this feed. In the future, let's post on Piazza for others to see as well
